remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
# Titel und Logo für dieses Theme
title: Frauenfeld Sightseeings Mattia
logo: ./https://img.chmedia.ch/2022/08/05/ffbe8176-135d-43d6-8df9-c668690cbf7e.jpeg?width=560&fit=crop&quality=75&auto=webp.jpeg
author: Mattia

