remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
# Titel und Logo für dieses Theme
title: Frauenfeld Sightseeings Mattia
logo: ./![F3355177-E555-4080-9685-AD78D350A500.png](F3355177-E555-4080-9685-AD78D350A500.png "Bild mit Hilfe von Draw Things erstellt.")
author: Mattia

